FROM debian:buster

# required package installation(s)
RUN apt-get update && \
    apt-get -y install openssh-server ssh software-properties-common python3-pip python3-dev libsasl2-dev libsasl2-2 libsasl2-modules-gssapi-mit

# upgrade pip and install jupyter
RUN pip3 install --upgrade pip
RUN pip install jupyter

# install python modules

RUN pip install sasl


RUN pip install six
RUN pip install bit-array
RUN pip install thriftpy2
RUN pip install thrift_sasl==0.4.2
RUN pip install impyla
RUN pip install pandas