FROM tbytnar/portable-hadoop:spark-base

ENV SPARK_MASTER_PORT 7077
ENV SPARK_MASTER_WEBUI_PORT 8080
ENV SPARK_MASTER_LOG /usr/local/spark/logs

ENTRYPOINT $SPARK_HOME/bin/spark-class org.apache.spark.deploy.master.Master