FROM tbytnar/portable-hadoop:spark-base

ENV MASTER_CONTAINER_NAME=sparkmaster
ENV CORES=1
ENV MEMORY=1G
ENV SPARK_WORKER_WEBUI_PORT 8081
ENV SPARK_WORKER_LOG /usr/local/spark/logs

ENTRYPOINT $SPARK_HOME/bin/spark-class org.apache.spark.deploy.worker.Worker -c $CORES -m $MEMORY spark://$MASTER_CONTAINER_NAME:7077